# -*- coding: utf-8 -*-
"""Bronze-Silver-OCI.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gT5Us4wCrkBoK6dfDkssktXMxPhK_ZJT

# 1 - Bibliotecas e Inicialização Spark
"""

import os
import pandas as pd
from datetime import datetime, date

from pyspark.sql.functions import col, count, when, isnan, countDistinct, approx_count_distinct, concat, col, lit, substring
from pyspark.sql.types import DoubleType, StringType, NumericType
from pyspark.sql.types import *
from pyspark.sql import functions as F
from pyspark.sql import SparkSession

from pyspark.ml.feature import VectorAssembler
from pyspark.ml.stat import Correlation

import os
from pyspark.sql import SparkSession

def get_spark_session(app_name="Hackathon_Project"):

    os.environ["OCI_IAM_TYPE"] = "resource_principal"


    spark = SparkSession.builder \
        .appName(app_name) \
        .config("spark.driver.memory", "20g") \
        .config("spark.executor.memory", "20g") \
        .config("spark.driver.maxResultSize", "4g") \
        .config("spark.hadoop.fs.oci.client.auth.kind", "resource_principal") \
        .config("spark.hadoop.fs.oci.client.regionCodeOrId", "us-chicago-1") \
        .config("spark.sql.parquet.datetimeRebaseModeInWrite", "LEGACY") \
        .config("spark.sql.parquet.datetimeRebaseModeInRead", "LEGACY") \
        .config("spark.sql.debug.maxToStringFields", "100") \
        .getOrCreate()


    hadoop_conf = spark.sparkContext._jsc.hadoopConfiguration()
    hadoop_conf.set("fs.oci.client.auth.kind", "resource_principal")
    hadoop_conf.set("fs.oci.client.regionCodeOrId", "us-chicago-1")
    hadoop_conf.set("fs.oci.client.custom.authenticator",
                    "com.oracle.bmc.hdfs.auth.ResourcePrincipalsCustomAuthenticator")

    return spark


spark = get_spark_session("Squad_06_Data_Prep")

"""#

# 2 - Carregando os dados

#
"""

path_bronze = "oci://layer-bronze@axshbddfc2lf"
dfs = {}

print('--- Carregando Bases Parquet ---')
dfs['cadastral'] = spark.read.parquet(f"{path_bronze}/base-dados-cadastrais/*.parquet")
dfs['score_bureau_full'] = spark.read.parquet(f"{path_bronze}/base-score-bureau-movel-full/*.parquet")
dfs['telco'] = spark.read.parquet(f"{path_bronze}/base-telco/*.parquet")
dfs['pagamento'] = spark.read.parquet(f"{path_bronze}/book-pagamento/*.parquet")
dfs['recarga'] = spark.read.parquet(f"{path_bronze}/bases-recarga/fato-parquet/*.parquet")

print('Carregado bases Parquet:', list(dfs.keys()))

print('\n--- Carregando CSVs (Dimensões Recarga) ---')

csvs_para_carregar = [
    'bi_dim_tipo_insercao',
    'bi_dim_promocao_credito',
    'bi_dim_canal_aquisicao_credito',
    'bi_dim_status_plataforma',
    'bi_dim_tipo_recarga',
    'bi_dim_plano_preco',
    'bi_dim_forma_pagamento',
    'bi_dim_instituicao',
    'bi_dim_plataforma',
    'bi_dim_tecnologia',
    'bi_dim_tipo_credito'
]

for nome_csv in csvs_para_carregar:
    try:
        caminho_csv = f'{path_bronze}/bases-recarga/dims-csv/{nome_csv.upper()}.csv'
        dfs[nome_csv] = spark.read.option('header', 'true').option('inferSchema', 'true').csv(caminho_csv)
        print(f'Carregado CSV: {nome_csv}')
    except Exception as e:
        print(f'Não foi possivel carregar {nome_csv}: {e}')

print('\n--PROCESSO DE LEITURA FINALIZADO--')

"""# 3 - Criação do ID unico e identificação do grupo controle

## 3.1 - Tabelas Com NUM_CPF e SAFRA
"""

#----------------------------------------------
# ID_UNICO -> NUM_CPF + SAFRA; e GRUPO_CONTROLE
#----------------------------------------------
tabelas_com_safra = ['cadastral', 'score_bureau_full', 'telco']

for tabela in tabelas_com_safra:

  # Criando ID_UNICO com NUM_CPF + SAFRA
  dfs[tabela] = dfs[tabela].withColumn(
      'ID_UNICO',
      concat(col('NUM_CPF'), col('SAFRA').cast('string'))
  )

  # Criando Flag do grupo controle GRUPO_CONTROLE
  # O grupo controle pode ser identificado a partir do 6º e 7º dígitos do CPF,
  # considerando as combinações ZZ e ZX.
  dfs[tabela] = dfs[tabela].withColumn(
      'GRUPO_CONTROLE',
      substring(col('NUM_CPF'), 6, 2).isin(['ZZ', 'ZX'])
  )

"""## 3.2 - Tabelas com NUM_CPF e sem SAFRA"""

#-----------------------------------
# Criação somente do GRUPO_CONTROLE
#-----------------------------------

tabelas_sem_safra = ['pagamento', 'recarga']

for tabela in tabelas_sem_safra:

  dfs[tabela] = dfs[tabela].withColumn(
      'GRUPO_CONTROLE',
      substring(col('NUM_CPF'), 6, 2).isin(['ZZ', 'ZX'])
  )

"""#

# 4 - Tratamento de Valores Ausentes

## 4.1 - Tabela cadastral
"""

df = dfs['cadastral']

df = df.withColumns({
    'SALARIO_FUNC_PUBL': F.coalesce(F.col('var_11').cast('double'), F.lit(-1.0)),
    'SALARIO_FUNC_PUBL_MISSING': F.when(F.col('var_11').isNotNull(), 0).otherwise(1),
    'CARGO_FUNC_PUBL': F.coalesce(F.col('var_10'), F.lit('NAO_APLICAVEL')),
    'FUNC_PUBL': F.when(F.col('var_20') == 'FUNC_PUBL', 1).otherwise(0),

    'var_02_missing': F.when(F.col('var_02').isNotNull(), 0).otherwise(1),
    'var_02' : F.coalesce(F.col('var_02').cast('double'), F.lit(-999)),

    'VALOR_EMPR_DIRETOR': F.coalesce(F.col('var_14').cast('float'), F.lit(-999)),
    'VALOR_EMPR_DIRETOR_MISSING': F.when(F.col('var_14').isNotNull(), 0).otherwise(1),
    'EMPR_DIRETOR': F.when(F.col('var_22').isNotNull(), 1).otherwise(0),
    'BOLSA_FAMILIA': F.when(F.col('var_23').isNotNull(), 1).otherwise(0),

    'SAFRA_BOLSA_FAMILIA': F.coalesce(F.col('var_17').cast('int'), F.lit(190001)),
    'SAFRA_BOLSA_FAMILIA_MISSING': F.when(F.col('var_17').isNotNull(), 0).otherwise(1),
    'UF_BOLSA_FAMILIA': F.coalesce(F.col('var_15'), F.lit('NAO_APLICAVEL')),
    'BENEFICIO_BOLSA_FAMILIA': F.coalesce(F.col('var_16').cast('float'), F.lit(0)),
    'BENEFICIO_BOLSA_FAMILIA_MISSING': F.when(F.col('var_16').isNotNull(), 0).otherwise(1),

    'var_07_MONETARIO': F.coalesce(F.col('var_07').cast('float'), F.lit(-999)),
    'var_07_MONETARIO_MISSING': F.when(F.col('var_07').isNotNull(), 0).otherwise(1),

    'NUMERO_APOSENTADO': F.coalesce(F.col('var_08').cast('int'), F.lit(-999)),
    'NUMERO_APOSENTADO_MISSING': F.when(F.col('var_08').isNotNull(), 0).otherwise(1),
    'APOSENTADO': F.when(F.col('var_18').isNotNull(), 1).otherwise(0),

    'AUXILLIO_EMERGENCIAL': F.when(F.col('var_19').isNotNull(), 1).otherwise(0),
    'MESES_AUXILIO_EMERGENCIAL': F.coalesce(F.col('var_09').cast('int'), F.lit(0)),
    'MESES_AUXILIO_EMERGENCIAL_MISSING': F.when(F.col('var_09').isNotNull(), 0).otherwise(1),

    'DATA_FUNC_PRIVADO': F.coalesce(F.to_date(F.col('var_12' ), 'dd/MM/yyyy'), F.lit('9999-01-01').cast('date')),
    'DATA_FUNC_PRIVADO_MISSING': F.when(F.col('var_12').isNotNull(), 0).otherwise(1),
    'FUNC_PRIVADO': F.when(F.col('var_21').isNotNull(), 1).otherwise(0),
    'STATUS_FUNC_PRIVADO': F.coalesce(F.col('var_24'), F.lit('NAO_APLICAVEL')),

    'flag_mig2': F.coalesce(F.col('flag_mig2'), F.lit('SEM_MIGRACAO')),

    'CONSOLIDADO': F.coalesce(F.col('var_25'), F.lit('SEM_INFORMACAO')),

    'CEP_3_digitos': F.coalesce(F.col('CEP_3_digitos'), F.lit('XXX')),

    'var_03': F.coalesce(F.col('var_03').cast('int'), F.lit(-1)),
    'var_03_MISSING': F.when(F.col('var_03') == -1, 1).otherwise(0),

    'var_05': F.coalesce(F.col('var_05').cast('int'), F.lit(-1)),
    'var_05_MISSING': F.when(F.col('var_05') == -1, 1).otherwise(0),

    'DATADENASCIMENTO': F.coalesce(F.to_date(F.col('DATADENASCIMENTO'), 'dd/MM/yyyy'), F.lit('1000-01-01').cast('date')),
    'DATADENASCIMENTO_MISSING': F.when(F.col('DATADENASCIMENTO') == '1000-01-01', 1).otherwise(0),

    'STATUSRF': F.coalesce(F.col('STATUSRF'), F.lit('SEM_STATUS')),
    'NUM_STATUSRF': F.coalesce(F.col('var_04').cast('int'), F.lit(-1))

}).drop('var_11', 'var_10', 'var_20', 'var_14', 'var_22', 'var_23', 'var_17', 'var_15', 'var_16',
        'var_07', 'var_13', 'var_08', 'var_18', 'var_06', 'var_19', 'var_09', 'var_12', 'var_21',
        'var_24','var_25', 'var_04')

ordem = ['ID_UNICO','GRUPO_CONTROLE','NUM_CPF','SAFRA','PROD', 'FLAG_INSTALACAO', 'flag_mig2','FPD', 'STATUSRF', 'NUM_STATUSRF',
         'DATADENASCIMENTO', 'DATADENASCIMENTO_MISSING','FUNC_PUBL', 'CARGO_FUNC_PUBL', 'SALARIO_FUNC_PUBL', 'SALARIO_FUNC_PUBL_MISSING',
         'EMPR_DIRETOR', 'VALOR_EMPR_DIRETOR', 'VALOR_EMPR_DIRETOR_MISSING', 'BOLSA_FAMILIA', 'SAFRA_BOLSA_FAMILIA', 'SAFRA_BOLSA_FAMILIA_MISSING',
         'UF_BOLSA_FAMILIA', 'BENEFICIO_BOLSA_FAMILIA', 'BENEFICIO_BOLSA_FAMILIA_MISSING', 'APOSENTADO', 'NUMERO_APOSENTADO', 'NUMERO_APOSENTADO_MISSING',
         'AUXILLIO_EMERGENCIAL', 'MESES_AUXILIO_EMERGENCIAL', 'MESES_AUXILIO_EMERGENCIAL_MISSING','FUNC_PRIVADO' , 'STATUS_FUNC_PRIVADO',
         'DATA_FUNC_PRIVADO', 'DATA_FUNC_PRIVADO_MISSING', 'CONSOLIDADO', 'CEP_3_digitos', 'var_07_MONETARIO', 'var_07_MONETARIO_MISSING',
         'var_02', 'var_02_missing', 'var_03', 'var_03_MISSING','var_05', 'var_05_MISSING']

df_save = df[ordem]

spark.conf.set("spark.sql.parquet.datetimeRebaseModeInWrite", "LEGACY")

path_silver_cadastro = "oci://layer-silver@axshbddfc2lf/tabela-cadastral"
df_save.write.mode("overwrite").partitionBy("SAFRA").parquet(path_silver_cadastro)

"""## 4.2 Tabela Telco"""

df = dfs['telco']

df = df.withColumns({

    'flag_mig2': F.coalesce(F.col('flag_mig2'), F.lit('SEM_MIGRACAO')),

    'var26_a_var77_MISSING': F.when(F.col("var_26").isNull(), 1).otherwise(0)

})

numericas_nulos = ['var_26', 'var_27', 'var_28', 'var_29', 'var_30', 'var_31', 'var_32', 'var_33', 'var_34', 'var_35', 'var_36', 'var_37', 'var_38',
 'var_39', 'var_40', 'var_41', 'var_42', 'var_43', 'var_44', 'var_45', 'var_46', 'var_47', 'var_48', 'var_49', 'var_50', 'var_51', 'var_52',
 'var_53', 'var_54', 'var_55', 'var_56', 'var_57', 'var_58', 'var_59', 'var_60', 'var_61', 'var_62', 'var_63', 'var_64', 'var_65', 'var_66',
 'var_67', 'var_68', 'var_69', 'var_70', 'var_71', 'var_72', 'var_73', 'var_74', 'var_75', 'var_76', 'var_77']

for col in numericas_nulos:
    df = df.withColumn(
        col,
        F.coalesce(F.col(col).cast('decimal(18,2)'), F.lit(-999))
    )

nao_nulas = ['var_78', 'var_79', 'var_80','var_81', 'var_82', 'var_83', 'var_84', 'var_85', 'var_86', 'var_87', 'var_88', 'var_89',
             'var_90', 'var_91', 'var_92', 'var_93']

for col in nao_nulas:
    df = df.withColumn(
        col,
        F.coalesce(F.col(col).cast('decimal(18,2)'), F.lit(-999))
    )

path_silver_telco = "oci://layer-silver@axshbddfc2lf/tabela-telco"
df.write.mode("overwrite")partitionBy("SAFRA").parquet(path_silver_telco)

"""## 4.3 Tabela score_bureau_full"""

df = dfs['score_bureau_full']

df = df.withColumns({
    'SCORE_01_MISSING': F.when(F.col('SCORE_01').isNull(), 1).otherwise(0),
    'SCORE_01': F.coalesce(F.col('SCORE_01').cast('int'), F.lit(-1)),

    'SCORE_02_MISSING': F.when(F.col('SCORE_02').isNull(), 1).otherwise(0),
    'SCORE_02': F.coalesce(F.col('SCORE_02').cast('int'), F.lit(-1))
})

df = df.select('ID_UNICO', 'GRUPO_CONTROLE', 'NUM_CPF', 'SAFRA', 'FLAG_INSTALACAO', 'PROD','FPD', 'flag_mig2',
               'SCORE_01', 'SCORE_01_MISSING', 'SCORE_02', 'SCORE_02_MISSING')

path_silver_score = "oci://layer-silver@axshbddfc2lf/tabela-score-bureau"
df.write.mode("overwrite")partitionBy("SAFRA").parquet(path_silver_score)

"""## 4.4 - Tabelas Dimensão

### 4.4.1 - bi_dim_tipo_insercao
"""

df = dfs['bi_dim_tipo_insercao']

df = df.withColumns({
    'DAT_CRIACAO_DW': F.to_date(F.col('DAT_CRIACAO_DW'), "ddMMMyyyy:HH:mm:ss"),
    'DAT_EXPIRACAO_DW': F.coalesce(F.col('DAT_EXPIRACAO_DW'), F.lit("9999-12-31").cast("date"))
})

path_silver_dim = "oci://layer-silver@axshbddfc2lf/tabela-bi-dim-tipo-insercao"
df.write.mode("overwrite").parquet(path_silver_dim)

"""### 4.4.2 - bi_dim_promocao_credito"""

df = dfs['bi_dim_promocao_credito']

df = df.withColumns({

    'DAT_EXPIRACAO_DW': F.coalesce(F.to_date(F.col('DAT_EXPIRACAO_DW'), "ddMMMyyyy:HH:mm:ss"), F.lit("9999-12-31").cast("date")),

    'DAT_ATUALIZACAO_DW': F.to_date(F.col('DAT_ATUALIZACAO_DW'), "ddMMMyyyy:HH:mm:ss"),

    'DAT_CRIACAO_DW': F.to_date(F.col('DAT_CRIACAO_DW'), "ddMMMyyyy:HH:mm:ss"),

    'DAT_INICIO_VIGENCIA': F.to_date(F.col('DAT_INICIO_VIGENCIA'), "ddMMMyyyy:HH:mm:ss"),

    'DAT_FIM_VIGENCIA': F.to_date(F.col('DAT_FIM_VIGENCIA'), "ddMMMyyyy:HH:mm:ss")
})

registro = [(-1, 'Não se aplica', date(9999,12,31), date(1900, 1, 1),date(1900, 1, 1), -1, 'Não se aplica', 'Não se aplica', date(1900, 1, 1), date(9999,12,31), -1.0, -1)]
df_extra = spark.createDataFrame(registro, schema = df.schema)

df = df.union(df_extra)

registro = [(-4, 'DESCONHECIDO', date(9999,12,31), date(1900, 1, 1),date(1900, 1, 1), -4, 'DESCONHECIDO', 'DESCONHECIDO', date(1900, 1, 1), date(9999,12,31), -4.0, -4)]
df_extra = spark.createDataFrame(registro, schema = df.schema)

df = df.union(df_extra)

path_silver_dim = "oci://layer-silver@axshbddfc2lf/tabela-bi-dim-promocao-credito"
df.write.mode("overwrite").parquet(path_silver_dim)

"""### 4.4.3 - bi_dim_canal_aquisicao_credito"""

df = dfs['bi_dim_canal_aquisicao_credito']

df = df.withColumns({
    'DAT_EXPIRACAO_DW': F.coalesce(F.to_date(F.col('DAT_EXPIRACAO_DW'), "ddMMMyyyy:HH:mm:ss"), F.lit("9999-12-31").cast("date")),

    'COD_TIPO_CREDITO': F.coalesce(F.col('COD_TIPO_CREDITO'), F.lit('NAO INFORMADO')),
    'COD_AGENTE_CREDITO': F.coalesce(F.col('COD_AGENTE_CREDITO'), F.lit('NAO INFORMADO')),

    'COD_TIPO_INSTITUICAO': F.coalesce(F.col('COD_TIPO_INSTITUICAO'), F.lit(-4)),
    'DSC_TIPO_INSTITUICAO': F.coalesce(F.col('DSC_TIPO_INSTITUICAO'), F.lit('DESCONHECIDO')),

    'DAT_ATUALIZACAO_DW': F.to_date(F.col('DAT_ATUALIZACAO_DW'), "ddMMMyyyy:HH:mm:ss"),
    'DAT_CRIACAO_DW': F.to_date(F.col('DAT_CRIACAO_DW'), "ddMMMyyyy:HH:mm:ss")
})

path_silver_dim = "oci://layer-silver@axshbddfc2lf/tabela-bi-dim-canal-aquisicao-credito"
df.write.mode("overwrite").parquet(path_silver_dim)

"""### 4.4.4 - bi_dim_status_plataforma"""

df = dfs['bi_dim_status_plataforma']

df = df.withColumns({
    'DAT_ATUALIZACAO_DW': F.to_date(F.col('DAT_ATUALIZACAO_DW'), "ddMMMyyyy:HH:mm:ss"),

    'DAT_CRIACAO_DW': F.to_date(F.col('DAT_CRIACAO_DW'), "ddMMMyyyy:HH:mm:ss")
})

path_silver_dim = "oci://layer-silver@axshbddfc2lf/tabela-bi-dim-status-plataforma"
df.write.mode("overwrite").parquet(path_silver_dim)

"""### 4.4.5 - bi_dim_tipo_recarga"""

df = dfs['bi_dim_tipo_recarga']

df = df.withColumns({
    'DAT_EXPIRACAO_DW': F.coalesce(F.to_date(F.col('DAT_EXPIRACAO_DW'), "ddMMMyyyy:HH:mm:ss"), F.lit("9999-12-31").cast("date")),
    'DAT_CRIACAO_DW': F.to_date(F.col('DAT_CRIACAO_DW'), "ddMMMyyyy:HH:mm:ss")
})

registro = [(-4, 'DESCONHECIDO', date(9999,12,31), date(1900, 1, 1))]
df_extra = spark.createDataFrame(registro, schema = df.schema)

df = df.union(df_extra)

path_silver_dim = "oci://layer-silver@axshbddfc2lf/tabela-bi-dim-tipo-recarga"
df.write.mode("overwrite").parquet(path_silver_dim)

"""### 4.4.6 - bi_dim_plano_preco"""

df = dfs['bi_dim_plano_preco']

df = df.withColumns({
    'DAT_EXPIRACAO_DW': F.coalesce(F.to_date(F.col('DAT_EXPIRACAO_DW'), "ddMMMyyyy:HH:mm:ss"), F.lit("9999-12-31").cast("date")),
    'DAT_EFETIVACAO': F.coalesce(F.to_date(F.col('DAT_EFETIVACAO'), "ddMMMyyyy:HH:mm:ss"), F.lit("1900-01-01").cast("date")),
    'DAT_EXPIRACAO': F.coalesce(F.to_date(F.col('DAT_EXPIRACAO'), "ddMMMyyyy:HH:mm:ss"), F.lit("9999-12-31").cast("date")),
    'DSC_PLANO_PRECO_UNICO_BI': F.coalesce(F.col('DSC_PLANO_PRECO_UNICO_BI'),F.lit('-4')),
    'COD_PLANO_COMPONENTE': F.coalesce(F.col('COD_PLANO_COMPONENTE'), F.lit(-4)),
    'NUM_FRANQUIA_VOLUME_BI': F.coalesce(F.col('NUM_FRANQUIA_VOLUME_BI').cast('int'), F.lit(-4)),
    'DSC_MODALIDADE_PLANO': F.coalesce(F.col('DSC_MODALIDADE_PLANO'), F.lit('DESCONHECIDO')),
    'NUM_FRANQUIA_REAIS_BI': F.coalesce(F.col('NUM_FRANQUIA_REAIS_BI').cast('int'), F.lit(-4)),
    'NUM_FRANQUIA_EVENTOS_BI': F.coalesce(F.col('NUM_FRANQUIA_EVENTOS_BI').cast('int'), F.lit(-4)),
    'NUM_FRANQUIA_MINUTOS_BI': F.coalesce(F.col('NUM_FRANQUIA_MINUTOS_BI').cast('int'), F.lit(-4)),
    'DAT_ATUALIZACAO_DW': F.to_date(F.col('DAT_ATUALIZACAO_DW'), "ddMMMyyyy:HH:mm:ss"),
    'DAT_CRIACAO_DW': F.to_date(F.col('DAT_CRIACAO_DW'), "ddMMMyyyy:HH:mm:ss")
})

registro = [(-4, '-4', '-4','-4','-4', 4, date(1900,1,1), date(9999,12,31),'-4', '-4', '-4', 'DESC', '-4',  -4, '-4', date(9999,12,31),date(1900,1,1), date(1900,1,1), -4, -4, -4, -4, -4, '-4', 'DESCONHECIDO')]
df_extra = spark.createDataFrame(registro, schema = df.schema)

df = df.union(df_extra)

path_silver_dim = "oci://layer-silver@axshbddfc2lf/tabela-bi-dim-plano-preco"
df.write.mode("overwrite").parquet(path_silver_dim)

"""### 4.4.7 - bi_dim_forma_pagamento"""

df = dfs['bi_dim_forma_pagamento']

df = df.withColumns({
    'DAT_CRIACAO_DW': F.to_date(F.col('DAT_CRIACAO_DW'), "ddMMMyyyy:HH:mm:ss"),

    'DAT_EXPIRACAO_DW': F.coalesce(F.to_date(F.col('DAT_EXPIRACAO_DW'), "ddMMMyyyy:HH:mm:ss"), F.lit("9999-12-31").cast("date"))
})

registro = [(-4, '-4', 'DESCONHECIDO', date(1900,1,1), date(9999,12,31))]
df_extra = spark.createDataFrame(registro, schema = df.schema)

df = df.union(df_extra)

path_silver_dim = "oci://layer-silver@axshbddfc2lf/tabela-bi-dim-forma-pagamento"
df.write.mode("overwrite").parquet(path_silver_dim)

"""### 4.4.8 - bi_dim_instituicao"""

df = dfs['bi_dim_instituicao']

df = df.withColumns({
    'DAT_CRIACAO_DW': F.to_date(F.col('DAT_CRIACAO_DW'), "ddMMMyyyy:HH:mm:ss"),
    'DAT_EXPIRACAO_DW': F.coalesce(F.to_date(F.col('DAT_EXPIRACAO_DW'), "ddMMMyyyy:HH:mm:ss"), F.lit("9999-12-31").cast("date"))
})

path_silver_dim = "oci://layer-silver@axshbddfc2lf/tabela-bi-dim-instituicao"
df.write.mode("overwrite").parquet(path_silver_dim)

"""### 4.4.9 - bi_dim_plataforma"""

df = dfs['bi_dim_plataforma']

df = df.withColumns({
    'DAT_EXPIRACAO_DW' : F.coalesce(F.to_date(F.col('DAT_EXPIRACAO_DW'), "ddMMMyyyy:HH:mm:ss"), F.lit("9999-12-31").cast("date")),
    'DAT_ATUALIZACAO_DW' : F.to_date(F.col('DAT_ATUALIZACAO_DW'), "ddMMMyyyy:HH:mm:ss"),
    'DAT_CRIACAO_DW': F.to_date(F.col('DAT_CRIACAO_DW'), "ddMMMyyyy:HH:mm:ss"),
    'DSC_GRUPO_PLATAFORMA' : F.coalesce(F.col('DSC_GRUPO_PLATAFORMA'), F.lit('Outros'))
})

registro = [(-4, '-4', date(9999,12,31), date(1900,1,1), date(1900,1,1), 'DESCONHECIDO', 'DESCONHECIDO', 'Outros')]
df_extra = spark.createDataFrame(registro, schema = df.schema)

df = df.union(df_extra)

path_silver_dim = "oci://layer-silver@axshbddfc2lf/tabela-bi-dim-plataforma"
df.write.mode("overwrite").parquet(path_silver_dim)

"""### 4.4.10 - bi_dim_tecnologia"""

df = dfs['bi_dim_tecnologia']

mask = "ddMMMyyyy:HH:mm:ss"
df = df.withColumns({
    'DAT_ATUALIZACAO_DW': F.coalesce(F.to_date(F.col('DAT_ATUALIZACAO_DW'), mask),
                                     F.to_date(F.lit('07MAY2010:11:23:38'), mask)),

    'DAT_CRIACAO_DW': F.to_date(F.col('DAT_CRIACAO_DW'), mask),
})

df = df.withColumns({
    'COD_TECNOLOGIA_SVA':  F.when(F.col('COD_TECNOLOGIA_DW') == '-1', 'Não se aplica').otherwise(F.col('COD_TECNOLOGIA_SVA')),
    'COD_TECNOLOGIA_SVA': F.when(F.col('COD_TECNOLOGIA_DW') == '-2', 'Não definido').otherwise(F.col('COD_TECNOLOGIA_SVA')),
    'COD_TECNOLOGIA_SVA': F.when(F.col('COD_TECNOLOGIA_DW') == '-3', 'Não informado').otherwise(F.col('COD_TECNOLOGIA_SVA')),
    'COD_TECNOLOGIA_SVA': F.coalesce(F.col('COD_TECNOLOGIA_SVA'), F.lit('DESCONHECIDO'))
})

path_silver_dim = "oci://layer-silver@axshbddfc2lf/tabela-bi-dim-tecnologia"
df.write.mode("overwrite").parquet(path_silver_dim)

"""### 4.4.11 - bi_dim_tipo_credito"""

df = dfs['bi_dim_tipo_credito']

mask = "ddMMMyyyy:HH:mm:ss"
df = df.withColumns({
    'DAT_ATUALIZACAO_DW': F.coalesce(F.to_date(F.col('DAT_ATUALIZACAO_DW'), mask),
                                     F.to_date(F.lit('19OCT2011:14:39:55'), mask)),

    'DAT_CRIACAO_DW': F.to_date(F.col('DAT_CRIACAO_DW'), mask),

    'DAT_EXPIRACAO_DW' : F.coalesce(F.col('DAT_EXPIRACAO_DW'), F.lit('9999-12-31'))

})

registro = [('-4', 'DESC', '9999-12-31', '1900-01-01', '1900-01-01')]

colunas = ["COD_TIPO_CREDITO", "DSC_TIPO_CREDITO", "DAT_EXPIRACAO_DW", "DAT_ATUALIZACAO_DW", "DAT_CRIACAO_DW"]
df_extra = spark.createDataFrame(registro, colunas)

df_extra = df_extra.withColumn("DAT_EXPIRACAO_DW", F.col("DAT_EXPIRACAO_DW").cast("date")) \
                   .withColumn("DAT_ATUALIZACAO_DW", F.col("DAT_ATUALIZACAO_DW").cast("date")) \
                   .withColumn("DAT_CRIACAO_DW", F.col("DAT_CRIACAO_DW").cast("date"))

df = df.union(df_extra)

path_silver_dim = "oci://layer-silver@axshbddfc2lf/tabela-bi-dim-tipo-credito"
df.write.mode("overwrite").parquet(path_silver_dim)

"""## 4.5 - Tabela recarga"""

df = dfs['recarga']

df = df.withColumns({
    'VALOR_SOS': F.coalesce(F.col('VALOR_SOS').cast('float'), F.lit(0)),
    'DW_TIPO_RECARGA': F.coalesce(F.col('DW_TIPO_RECARGA').cast('int'), F.lit(-4)),
    'DW_PLANO_TARIFACAO': F.coalesce(F.col('DW_PLANO_TARIFACAO').cast('int'), F.lit(-4)),
    'COD_PROMOCAO' : F.coalesce(F.col('COD_PROMOCAO').cast('int'), F.lit(-4)),
    'DAT_INSERCAO_CREDITO': F.to_date(F.col('DAT_INSERCAO_CREDITO'), "ddMMMyyyy:HH:mm:ss")
})

valor_bigint = ['DW_NUM_NTC',  'DW_NUM_CLIENTE',]
valor_int = ['COD_CANAL_AQUISICAO', 'HOR_INSERCAO_CREDITO','DW_TIPO_INSERCAO','DW_FORMA_PAGAMENTO','DW_INSTITUICAO', 'FLAG_SOS']
valor_float = ['VAL_CREDITO_INSERIDO', 'VAL_BONUS', 'VAL_REAl', ]

for coluna in valor_bigint:
  df = df.withColumn(
      coluna,
      F.col(coluna).cast('bigint')
  )

for coluna in valor_int:
  df = df.withColumn(
      coluna,
      F.col(coluna).cast('int')
  )

for coluna in valor_float:
  df = df.withColumn(
      coluna,
      F.col(coluna).cast('float')
  )

#Salvament
# Criando colunas de Ano e Mês para particionamento
df = df.withColumn('ANO_INSERCAO', year('DAT_INSERCAO_CREDITO')) \
       .withColumn('MES_INSERCAO', month('DAT_INSERCAO_CREDITO'))

path_silver_recarga = "oci://layer-silver@axshbddfc2lf/tabela-recarga"
df.write.mode("overwrite").partitionBy("ANO_INSERCAO", "MES_INSERCAO").parquet(path_silver_recarga)

"""## 4.6 Tabela pagamento"""

df = dfs['pagamento']

NULOS_100 = ['COD_NETUNO_PAGAMENTO', 'COD_DESALOCACAO_CREDITO', 'DAT_ATUALIZACAO_CREDITO']

for coluna in NULOS_100:
  df = df.withColumn(
      coluna,
      F.coalesce(F.col(coluna), F.lit('DESCONHECIDO'))
  )

df = df.withColumns({
    'COD_FUNDO_ATIVIDADE': F.coalesce(F.col('COD_FUNDO_ATIVIDADE').cast('int'), F.lit(-4)),
    'COD_FUNDO_ATIVIDADE_MISSING': F.when(F.col('COD_FUNDO_ATIVIDADE') == -4, 1).otherwise(0),

    'NUM_PARCELA_PAGAMENTO': F.coalesce(F.col('NUM_PARCELA_PAGAMENTO').cast('int'), F.lit(-4)),
    'NUM_PARCELA_PAGAMENTO_MISSING': F.when(F.col('NUM_PARCELA_PAGAMENTO') == -4, 1).otherwise(0),

    'DAT_ATUALIZACAO_ATIVIDADE': F.coalesce(F.to_date(F.col('DAT_ATUALIZACAO_ATIVIDADE'), "ddMMMyyyy:HH:mm:ss"), F.lit('1900-01-01').cast("date")),
    'DAT_ATUALIZACAO_ATIVIDADE_MISSING' : F.when(F.col('DAT_ATUALIZACAO_ATIVIDADE') == '1900-01-01', 1).otherwise(0),

    'NUM_CONTA_ATIVIDADE': F.coalesce(F.col('NUM_CONTA_ATIVIDADE'), F.lit('-4')),

    'DAT_ATUALIZACAO_PAGAMENTO_MISSING': F.when(F.col('DAT_ATUALIZACAO_PAGAMENTO').isNull(), 1).otherwise(0),
    'DAT_ATUALIZACAO_PAGAMENTO' : F.coalesce(F.to_date(F.col('DAT_ATUALIZACAO_PAGAMENTO'), "ddMMMyyyy:HH:mm:ss"), F.lit('1900-01-01').cast("date")),

    'DSC_PAGAMENTO': F.coalesce(F.col('DSC_PAGAMENTO'), F.lit('DESCONHECIDO')),

    'COD_ARQUIVO_PAGAMENTO': F.coalesce(F.col('COD_ARQUIVO_PAGAMENTO'), F.lit('DESCONHECIDO')),

    'COD_METODO_PAGAMENTO': F.coalesce(F.col('COD_METODO_PAGAMENTO').cast('int'), F.lit(-4)),

    'NUM_AGRUPADOR_MISSING': F.when(F.col('NUM_AGRUPADOR_PAGAMENTO').isNull(), 1).otherwise(0),
    'NUM_AGRUPADOR_PAGAMENTO': F.coalesce(F.col('NUM_AGRUPADOR_PAGAMENTO').cast('int'), F.lit(-4)),

    'COD_AGENCIA_ATIVIDADE': F.coalesce(F.col('COD_AGENCIA_ATIVIDADE'), F.lit('-4')),

    'COD_LOGIN_PAGAMENTO_MISSING': F.when(F.col('COD_LOGIN_PAGAMENTO').isNull(), 1).otherwise(0),
    'COD_LOGIN_PAGAMENTO': F.coalesce(F.col('COD_LOGIN_PAGAMENTO').cast('int'), F.lit(-4)),

    'COD_LOGIN_CREDITO_MISSING': F.when(F.col('COD_LOGIN_CREDITO').isNull(), 1).otherwise(0),
    'COD_LOGIN_CREDITO': F.coalesce(F.col('COD_LOGIN_CREDITO').cast('int'), F.lit(-4)),

    'COD_LOGIN_OPERADOR_ATIVIDADE_MISSING': F.when(F.col('COD_LOGIN_OPERADOR_ATIVIDADE').isNull(), 1).otherwise(0),
    'COD_LOGIN_OPERADOR_ATIVIDADE': F.coalesce(F.col('COD_LOGIN_OPERADOR_ATIVIDADE').cast('int'), F.lit(-4)),

    'SEQ_ARQUIVO_PAGAMENTO_MISSING': F.when(F.col('SEQ_ARQUIVO_PAGAMENTO').isNull(), 1).otherwise(0),
    'SEQ_ARQUIVO_PAGAMENTO': F.coalesce(F.col('SEQ_ARQUIVO_PAGAMENTO').cast('int'), F.lit(-4)),

    'COD_BANCO_ATIVIDADE': F.coalesce(F.col('COD_BANCO_ATIVIDADE'), F.lit('DESCONHECIDO')),

    'COD_ORIGEM_NETUNO': F.coalesce(F.col('COD_ORIGEM_NETUNO'), F.lit('DESCONHECIDO')),

    'IND_STATUS_PAGAMENTO': F.coalesce(F.col('IND_STATUS_PAGAMENTO'), F.lit('-4')),

    'COD_RAZAO_ATIVIDADE': F.coalesce(F.col('COD_RAZAO_ATIVIDADE'), F.lit('DESCONHECIDO')),

    'NUM_FATURA_PAGAMENTO': F.coalesce(F.col('NUM_FATURA_PAGAMENTO'), F.lit('DESCONHECIDO')),

    'VAL_ATUAL_PAGAMENTO_MISSING': F.when(F.col('VAL_ATUAL_PAGAMENTO').isNull(), 1).otherwise(0),
    'VAL_ATUAL_PAGAMENTO': F.coalesce(F.col('VAL_ATUAL_PAGAMENTO').cast('float'), F.lit(-4.0)),

    'BLOCO_28-03-percet_MISSING': F.when(F.col('SEQ_FATURA_CREDITO').isNull(), 1).otherwise(0),

    'SEQ_FATURA_CREDITO': F.coalesce(F.col('SEQ_FATURA_CREDITO').cast('int'), F.lit(-4)),
    'SEQ_PAGAMENTO_CREDITO': F.coalesce(F.col('SEQ_PAGAMENTO_CREDITO').cast('int'), F.lit(-4)),
    'SEQ_ENTIDADE_PAGAMENTO': F.coalesce(F.col('SEQ_ENTIDADE_PAGAMENTO').cast('int'), F.lit(-4)),
    'SEQ_ENTIDADE_ATIVIDADE': F.coalesce(F.col('SEQ_ENTIDADE_ATIVIDADE').cast('int'), F.lit(-4)),
    'SEQ_ENTIDADE_CREDITO': F.coalesce(F.col('SEQ_ENTIDADE_CREDITO').cast('int'), F.lit(-4)),

    'VAL_PAGAMENTO_CREDITO': F.coalesce(F.col('VAL_PAGAMENTO_CREDITO').cast('float'), F.lit(-4.0)),
    'VAL_ORIGINAL_PAGAMENTO': F.coalesce(F.col('VAL_ORIGINAL_PAGAMENTO').cast('float'), F.lit(-4.0)),
    'VAL_BAIXA_ATIVIDADE': F.coalesce(F.col('VAL_BAIXA_ATIVIDADE').cast('float'), F.lit(-444444.0)),

    'DAT_STATUS_PAGAMENTO': F.coalesce(F.to_date(F.col('DAT_STATUS_PAGAMENTO'), "ddMMMyyyy:HH:mm:ss"), F.lit('1900-01-01').cast("date")),
    'DAT_CRIACAO_CREDITO': F.coalesce(F.to_date(F.col('DAT_CRIACAO_CREDITO'), "ddMMMyyyy:HH:mm:ss"), F.lit('1900-01-01').cast("date")),
    'DAT_CRIACAO_PAGAMENTO': F.coalesce(F.to_date(F.col('DAT_CRIACAO_PAGAMENTO'), "ddMMMyyyy:HH:mm:ss"), F.lit('1900-01-01').cast("date")),
    'DAT_ATIVIDADE_CREDITO': F.coalesce(F.to_date(F.col('DAT_ATIVIDADE_CREDITO'), "ddMMMyyyy:HH:mm:ss"), F.lit('1900-01-01').cast("date")),
    'DAT_BAIXA_ATIVIDADE': F.coalesce(F.to_date(F.col('DAT_BAIXA_ATIVIDADE'), "ddMMMyyyy:HH:mm:ss"), F.lit('9999-12-31').cast("date")),
    'DAT_DEPOSITO_ATIVIDADE': F.coalesce(F.to_date(F.col('DAT_DEPOSITO_ATIVIDADE'), "ddMMMyyyy:HH:mm:ss"), F.lit('9999-12-31').cast("date")),
    'DAT_CRIACAO_ATIVIDADE': F.coalesce(F.to_date(F.col('DAT_CRIACAO_ATIVIDADE'), "ddMMMyyyy:HH:mm:ss"), F.lit('1900-01-01').cast("date")),
    'DAT_VENCIMENTO_CREDITO' : F.coalesce(F.to_date(F.col('DAT_VENCIMENTO_CREDITO'), "ddMMMyyyy:HH:mm:ss"), F.lit('9999-12-31').cast("date")),

    'IND_TIPO_CREDITO': F.coalesce(F.col('IND_TIPO_CREDITO'), F.lit('DESCONHECIDO')),

    'DSC_NOME_BANCO_PAGAMENTO': F.coalesce(F.col('DSC_NOME_BANCO_PAGAMENTO'), F.lit('DESCONHECIDO')),

    'COD_TIPO_PAGAMENTO': F.coalesce(F.col('COD_TIPO_PAGAMENTO'), F.lit('DESCONHECIDO')),
    'COD_FORMA_PAGAMENTO': F.coalesce(F.col('COD_FORMA_PAGAMENTO'), F.lit('DESCONHECIDO')),
    'COD_TIPO_FATURA': F.coalesce(F.col('COD_TIPO_FATURA'), F.lit('DESCONHECIDO')),
    'COD_ALOCACAO_CREDITO': F.coalesce(F.col('COD_ALOCACAO_CREDITO'), F.lit('DESCONHECIDO')),
    'COD_CONTA_ATIVIDADE': F.coalesce(F.col('COD_CONTA_ATIVIDADE'), F.lit('DESCONHECIDO')),
    'COD_ATIVIDADE': F.coalesce(F.col('COD_ATIVIDADE'), F.lit('DESCONHECIDO'))
})

datas = ['DAT_STATUS_FATURA', 'DAT_CRIACAO_DW', 'DAT_CRIACAO_ATIVIDADE', 'DAT_ATUALIZACAO_ATIVIDADE', 'DAT_BAIXA_ATIVIDADE', 'DAT_DEPOSITO_ATIVIDADE', 'DAT_CRIACAO_PAGAMENTO', 'DAT_ATUALIZACAO_PAGAMENTO',
         'DAT_STATUS_PAGAMENTO', 'DAT_CRIACAO_CREDITO',  'DAT_ATIVIDADE_CREDITO','DAT_VENCIMENTO_CREDITO' ]

for coluna in datas:
  df = df.withColumn(
      coluna,
      F.to_date(F.col(coluna), "ddMMMyyyy:HH:mm:ss")
  )

valores = ['VAL_DESCONTO_ITEM','VAL_PAGAMENTO_ITEM', 'VAL_JUROS_MULTAS_ITEM', 'VAL_MULTA_EQUIP_ITEM', 'VAL_MULTA_EQUIP_TOTAL', 'VAL_MULTA_FID_ITEM' ]

for coluna in valores:
    df = df.withColumn(
        coluna,
        F.coalesce(F.col(coluna).cast('float'), F.lit(0.0))
    )

# Salvamento
# Criando colunas de Ano e Mês para particionamento
df = df.withColumn('ANO_FATURA', year('DAT_STATUS_FATURA')) \
       .withColumn('MES_FATURA', month('DAT_STATUS_FATURA'))

path_silver_pagamento = "oci://layer-silver@axshbddfc2lf/tabela-pagamento"
df.write.mode("overwrite").partitionBy("ANO_FATURA", "MES_FATURA").parquet(path_silver_pagamento)